#!/bin/bash
erreurspossibles='Erreurs possibles:\n\t1.\tfichier "MakeFile" modifié ou inexistant\n\t2.\tcommande "make" non reconnu par votre OS\n'
msgerreur='\n############################\n\ncompilation: erreur !\n\n############################\n'
msgGood='\n############################\n\ncompilation: aucun probleme !\n\n############################\n'
executable="main"

if make; then
    echo -e $msgGood
    ./$executable
else
    echo -e $msgerreur
    exit 1
fi
